<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Login</name>
   <tag></tag>
   <elementGuidId>ccd2050f-cd06-4314-9b3b-1d360e1e31a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;login&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9245c023-5829-4af6-8776-ab79e6cd1090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm input-sm ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>775c95e4-3fe5-4f28-baac-c3e3882adc3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>8bd074b5-8ce8-435a-bfa1-069399f61845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>be8daf28-3661-4c69-baf0-0b4d323d296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9c27a800-9e8f-41f4-993d-0e22c49ebb9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/header[1]/nav[@class=&quot;navbar navbar-full navbar-dark bg-inverse&quot;]/div[@class=&quot;container&quot;]/my-login[1]/div[@class=&quot;pull-xs-right&quot;]/form[@class=&quot;form-inline&quot;]/div[@class=&quot;form-group&quot;]/input[@class=&quot;form-control form-control-sm input-sm ng-untouched ng-pristine ng-invalid&quot;]</value>
      <webElementGuid>c02b0bd0-bb93-47eb-a5b7-54ca28af7995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='login']</value>
      <webElementGuid>3f49c7ab-c816-4272-9c9a-f09097f74362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0194342a-a603-4ac2-8eb6-16ce11593e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @placeholder = 'Login' and @type = 'text']</value>
      <webElementGuid>6b0ab29f-0b11-4257-a60f-b944f71ab416</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
